name: studle
description: "Application for students to research their data and performance at school"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  validatorless: ^1.2.3
  provider: ^6.1.2
  phosphor_flutter: ^2.0.1
  result_dart: ^1.1.0
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  collection: ^1.18.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  mask_text_input_formatter: ^2.9.0
  flutter_bloc: ^8.1.4
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^24.2.9
  uuid: ^4.3.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  app_settings: ^5.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf

flutter_launcher_icons:
  image_path: "assets/icon-ios.png"
  adaptive_icon_foreground: "assets/icon-android.png"
  android: true
  ios: true
  adaptive_icon_background: "#4723D9"